/**
 * Data endpoints served by worker-seo, all with `access-control-allow-origin: *`
 * so they fetch fine cross-origin from the Shopify storefront.
 *
 * NONE of these exist yet — they are the data contracts from SCOPE.md, to be
 * generated by worker-seo/scripts/* from seed data (mirror WhollyKaw's
 * build-scent-routines.mjs). The brew-guide widget needs none of them (its
 * preparation params are inline); this module scaffolds the later widgets:
 *
 *   /learn/products.json          [{ handle, title, price, variantId }]  (#1 #3)
 *   /learn/tea-finder.json        attribute map for the finder quiz       (#1)
 *   /learn/ingredient-safety.json ingredient × audience safety tones      (#4)
 *   /learn/caffeine.json          [{ tea, mgPerCup, source }]             (#6)
 */
const ORIGIN = 'https://tmolecule.com';

export const ENDPOINTS = {
  products: `${ORIGIN}/learn/products.json`,
  teaFinder: `${ORIGIN}/learn/tea-finder.json`,
  ingredientSafety: `${ORIGIN}/learn/ingredient-safety.json`,
  caffeine: `${ORIGIN}/learn/caffeine.json`,
};

export async function getJson(url) {
  const res = await fetch(url, { credentials: 'omit' });
  if (!res.ok) throw new Error(`fetch ${url} -> ${res.status}`);
  return res.json();
}

let _products = null;
/** Returns the 2 TM products, or false if the endpoint isn't built yet. */
export async function loadProducts() {
  if (_products !== null) return _products;
  try {
    const data = await getJson(ENDPOINTS.products);
    _products = Array.isArray(data) && data.length ? data : false;
  } catch {
    _products = false; // caller falls back to inline product constants
  }
  return _products;
}
