#!/usr/bin/env python3
"""Send TMolecule accessibility audit email via Resend HTTP API.
Usage:
  send-audit-email.py start
  send-audit-email.py finish <status: PASS|FAIL> <log-path>

Env vars required:
  RESEND_API_KEY
  RESEND_TO
  RESEND_FROM (optional — defaults to 'TMolecule Audits <audits@tmolecule.com>')
  RUN_URL    (optional — GitHub Actions run URL to link)
  RUN_DATE   (optional — ISO date stamp for subject)
"""
import os, sys, json, urllib.request
from pathlib import Path
from datetime import datetime, timezone

RESEND_API_KEY = os.environ['RESEND_API_KEY']
RESEND_TO      = os.environ['RESEND_TO']
RESEND_FROM    = os.environ.get('RESEND_FROM', 'TMolecule Audits <audits@tmolecule.com>')
RUN_URL        = os.environ.get('RUN_URL', '')
RUN_DATE       = os.environ.get('RUN_DATE') or datetime.now(timezone.utc).strftime('%Y-%m-%d')
RUN_ISO        = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

# --- Warm TMolecule palette (inline styles for maximum email-client compat) ---
PALETTE = {
    'bg':         '#faf7f0',
    'panel':      '#fefaf0',
    'rule':       '#e3dbc9',
    'ink':        '#1a1816',
    'muted':      '#8a7a60',
    'terra':      '#c87040',
    'terra_dark': '#a85830',
    'cream_text': '#faf3e0',
    'pass_bg':    '#e8f0dc',
    'pass_text':  '#3a5a28',
    'fail_bg':    '#fce8e0',
    'fail_text':  '#8a2818',
}

REPORT_NAME = 'Monthly Accessibility Audit · tmolecule.com'
REPORT_DESCRIPTION_HTML = """
  <p style="margin:0 0 10px;">Automated <strong>WCAG 2.1 Level AA</strong> scan of the seven public pages on tmolecule.com (Home, Shop, Product, Cart, About, Contact, Accessibility), run via <strong>axe-core v4.10</strong>.</p>
  <p style="margin:0 0 6px;font-size:13px;color:#4a4038;">Every run checks each page for:</p>
  <ul style="margin:0 0 10px;padding-left:20px;font-size:14px;color:#4a4038;">
    <li>Color contrast (4.5:1 text · 3:1 large text · 3:1 UI)</li>
    <li>Form labels, ARIA usage, heading order</li>
    <li>Keyboard focus indicators and tab order</li>
    <li>Landmarks, language attributes, image alt text</li>
  </ul>
  <p style="margin:0;font-size:13px;color:#4a4038;">The dated JSON result is saved to the repo for audit trail and regression tracking.</p>
"""

def html_shell(body_inner, pre_header):
    """Wrap inner HTML in the standard TMolecule email chrome."""
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{{margin:0;padding:0;}}</style></head>
<body style="margin:0;padding:0;background:{PALETTE['bg']};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;color:{PALETTE['ink']};">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">{pre_header}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:{PALETTE['bg']};padding:32px 16px;">
  <tr><td align="center">
    <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background:{PALETTE['panel']};border:1px solid {PALETTE['rule']};border-radius:14px;overflow:hidden;box-shadow:0 8px 24px rgba(74,55,24,.12);">
      <tr><td style="background:{PALETTE['terra_dark']};padding:24px 32px;border-bottom:4px solid {PALETTE['terra']};">
        <p style="margin:0 0 4px;text-transform:uppercase;letter-spacing:.2em;font-size:10px;font-weight:800;color:{PALETTE['cream_text']};opacity:.75;">Automated report · tmolecule.com</p>
        <h1 style="margin:0;font-family:Georgia,'Times New Roman',serif;font-size:22px;line-height:1.2;color:{PALETTE['cream_text']};font-weight:700;letter-spacing:-.01em;">{REPORT_NAME}</h1>
      </td></tr>
      <tr><td style="padding:28px 32px;font-size:14.5px;line-height:1.6;">{body_inner}</td></tr>
      <tr><td style="padding:18px 32px;background:{PALETTE['bg']};border-top:1px solid {PALETTE['rule']};font-size:12px;color:{PALETTE['muted']};">
        <p style="margin:0 0 4px;">Next scheduled run · 3rd of next month at 09:07 ET (13:07 UTC)</p>
        <p style="margin:0;">TMolecule accessibility automation · generated by GitHub Actions</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body></html>"""

def h2(text):
    return f'<h2 style="margin:24px 0 10px;font-family:Georgia,serif;font-size:17px;font-weight:700;color:{PALETTE["ink"]};letter-spacing:-.01em;border-bottom:1px solid {PALETTE["rule"]};padding-bottom:6px;">{text}</h2>'

def kv_table(pairs):
    rows = ''.join(
        f'<tr><td style="padding:5px 14px 5px 0;font-size:13px;color:{PALETTE["muted"]};white-space:nowrap;vertical-align:top;width:100px;">{k}</td>'
        f'<td style="padding:5px 0;font-size:13px;color:{PALETTE["ink"]};font-family:Menlo,Monaco,monospace;word-break:break-all;">{v}</td></tr>'
        for k, v in pairs
    )
    return f'<table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:4px 0 8px;">{rows}</table>'

def status_badge(status, status_line):
    color_bg   = PALETTE['pass_bg']   if status == 'PASS' else PALETTE['fail_bg']
    color_text = PALETTE['pass_text'] if status == 'PASS' else PALETTE['fail_text']
    icon = '✓' if status == 'PASS' else '✗'
    return (f'<div style="background:{color_bg};border:1px solid {color_text}22;border-radius:10px;padding:14px 18px;margin:12px 0 8px;">'
            f'<p style="margin:0;font-size:15px;font-weight:700;color:{color_text};">{icon} {status} — {status_line}</p>'
            f'</div>')

def stats_table_from_log(log_path):
    """Parse the plain-text stats log and build an HTML table."""
    try:
        lines = Path(log_path).read_text().strip().splitlines()
    except Exception:
        return '<p style="color:#8a2818;font-style:italic;">Stats log not available.</p>'
    # Find the rows: "  Home                 0  0  0  0"
    rows = []
    for ln in lines:
        ln = ln.rstrip()
        if not ln or ln.startswith('TMolecule') or 'critical' in ln.lower() or ln.startswith('Report'):
            continue
        parts = ln.split()
        if len(parts) >= 5 and parts[-4].isdigit() and parts[-3].isdigit() and parts[-2].isdigit() and parts[-1].isdigit():
            name = ' '.join(parts[:-4])
            nums = parts[-4:]
            rows.append((name, *nums))
    if not rows:
        return f'<pre style="background:#f0e8d8;padding:12px;border-radius:8px;font-size:12px;white-space:pre-wrap;">{Path(log_path).read_text()}</pre>'

    def cell(v, is_num=False, is_total=False):
        color = PALETTE['ink'] if v == '0' else PALETTE['fail_text']
        weight = '800' if is_total else ('700' if v != '0' else '500')
        return f'<td style="padding:8px 10px;border-bottom:1px solid {PALETTE["rule"]};font-size:13px;color:{color};font-weight:{weight};text-align:{"right" if is_num else "left"};font-family:{"Menlo,Monaco,monospace" if is_num else "inherit"};">{v}</td>'

    header = ('<thead><tr>'
              f'<th style="padding:10px 10px;border-bottom:2px solid {PALETTE["rule"]};font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:{PALETTE["muted"]};font-weight:700;text-align:left;">Page</th>'
              f'<th style="padding:10px 10px;border-bottom:2px solid {PALETTE["rule"]};font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:{PALETTE["muted"]};font-weight:700;text-align:right;">Critical</th>'
              f'<th style="padding:10px 10px;border-bottom:2px solid {PALETTE["rule"]};font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:{PALETTE["muted"]};font-weight:700;text-align:right;">Serious</th>'
              f'<th style="padding:10px 10px;border-bottom:2px solid {PALETTE["rule"]};font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:{PALETTE["muted"]};font-weight:700;text-align:right;">Moderate</th>'
              f'<th style="padding:10px 10px;border-bottom:2px solid {PALETTE["rule"]};font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:{PALETTE["muted"]};font-weight:700;text-align:right;">Minor</th>'
              '</tr></thead>')
    body = ''
    for i, (name, c, s, mod, mn) in enumerate(rows):
        is_total = name.upper() == 'TOTAL'
        name_cell = f'<td style="padding:8px 10px;border-bottom:1px solid {PALETTE["rule"]};font-size:14px;color:{PALETTE["ink"]};font-weight:{"700" if is_total else "500"};">{name}</td>'
        body += f'<tr>{name_cell}{cell(c, True, is_total)}{cell(s, True, is_total)}{cell(mod, True, is_total)}{cell(mn, True, is_total)}</tr>'
    return f'<table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:4px 0 8px;border-collapse:collapse;">{header}<tbody>{body}</tbody></table>'

def action_required_block():
    return (f'<div style="background:{PALETTE["bg"]};border-left:4px solid {PALETTE["terra_dark"]};border-radius:6px;padding:14px 18px;margin:18px 0;">'
            f'<p style="margin:0 0 8px;font-weight:800;color:{PALETTE["terra_dark"]};font-size:13px;letter-spacing:.08em;text-transform:uppercase;">Action required</p>'
            f'<p style="margin:0 0 10px;font-size:14px;">Update the audit date on the public accessibility statement so <code style="background:{PALETTE["panel"]};padding:1px 5px;border-radius:3px;font-size:12px;">/pages/accessibility</code> stays current:</p>'
            f'<ol style="margin:0 0 6px;padding-left:20px;font-size:14px;line-height:1.55;">'
            f'<li>Shopify Admin → <em>Customize</em></li>'
            f'<li>Navigate to <em>Pages → Accessibility</em></li>'
            f'<li>Open the <em>TMolecule accessibility</em> section settings</li>'
            f'<li>Change <strong>Last audit date</strong> to <code style="background:{PALETTE["panel"]};padding:1px 5px;border-radius:3px;font-size:12px;">{RUN_DATE}</code></li>'
            f'<li>(optional) set <strong>Statement last updated</strong> to today</li>'
            f'<li>Save and publish</li>'
            f'</ol>'
            f'<p style="margin:8px 0 0;font-size:12px;color:{PALETTE["muted"]};">Auditors and complainants will check that date.</p>'
            f'</div>')

def cta_link(text, url):
    return (f'<a href="{url}" style="display:inline-block;background:{PALETTE["terra_dark"]};color:{PALETTE["cream_text"]};padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:700;font-size:13px;letter-spacing:.06em;text-transform:uppercase;">{text}</a>')

# ---------- Build payload ----------

mode = sys.argv[1] if len(sys.argv) > 1 else 'start'

if mode == 'start':
    subject = f'[Monthly a11y audit · STARTED] tmolecule.com · {RUN_DATE}'
    pre_header = f'Starting WCAG 2.1 AA scan for {RUN_DATE} · stats in ~2 min'
    inner = (
        h2('About this report')
        + REPORT_DESCRIPTION_HTML
        + h2('Run details')
        + kv_table([
            ('Status',   '<span style="color:'+PALETTE['terra_dark']+';font-weight:800;">STARTING</span>'),
            ('Time',     RUN_ISO),
            ('Target',   '<a href="https://tmolecule.com" style="color:'+PALETTE['terra_dark']+';">https://tmolecule.com</a>'),
            ('Scope',    '7 pages · WCAG 2.1 AA'),
            ('Runner',   'GitHub Actions · ubuntu-latest'),
        ])
        + (f'<p style="margin:18px 0 0;"><a href="{RUN_URL}" style="color:{PALETTE["terra_dark"]};font-weight:700;">View live run →</a></p>' if RUN_URL else '')
        + f'<p style="margin:18px 0 0;color:{PALETTE["muted"]};font-size:13px;font-style:italic;">A second email with the full per-page stats and action-required items will follow when the run finishes.</p>'
    )
elif mode == 'finish':
    status = sys.argv[2] if len(sys.argv) > 2 else 'PASS'
    log_path = sys.argv[3] if len(sys.argv) > 3 else None
    status_line = ('0 critical / 0 serious WCAG 2.1 AA violations across all pages' if status == 'PASS'
                   else 'critical or serious violations detected — see stats')
    subject = f'[Monthly a11y audit · FINISHED · {status}] tmolecule.com · {RUN_DATE}'
    pre_header = f'{status} · {status_line}'
    inner = (
        h2('About this report')
        + REPORT_DESCRIPTION_HTML
        + h2('Result')
        + status_badge(status, status_line)
        + h2('Per-page stats')
        + (stats_table_from_log(log_path) if log_path else '<p>No stats log attached.</p>')
        + h2('Action required')
        + action_required_block()
        + h2('Artifacts')
        + kv_table([
            ('JSON',    f'<code>audits/axe-{RUN_DATE}.json</code> (committed to repo)'),
            ('Log',     f'<code>audits/axe-{RUN_DATE}.log</code>'),
            ('Retain',  '90 days on GitHub Actions · indefinite in git'),
        ])
        + (f'<p style="margin:20px 0 0;">{cta_link("View run on GitHub", RUN_URL)}</p>' if RUN_URL else '')
    )
else:
    print(f'Unknown mode: {mode}', file=sys.stderr)
    sys.exit(2)

html = html_shell(inner, pre_header)
payload = {
    'from':    RESEND_FROM,
    'to':      [RESEND_TO],
    'subject': subject,
    'html':    html,
}

req = urllib.request.Request(
    'https://api.resend.com/emails',
    data=json.dumps(payload).encode(),
    headers={
        'Authorization': f'Bearer {RESEND_API_KEY}',
        'Content-Type':  'application/json',
        'User-Agent':    'TMolecule-AuditBot/1.0 (+https://tmolecule.com)',
        'Accept':        'application/json',
    },
)
try:
    with urllib.request.urlopen(req, timeout=15) as resp:
        body = resp.read().decode()
        print(f'Resend {resp.status}: {body[:200]}')
except urllib.error.HTTPError as e:
    print(f'Resend ERROR {e.code}: {e.read().decode()[:400]}', file=sys.stderr)
    sys.exit(1)
